### ISSUE TITLE
'NeuroMap 2.csv' is missing in the repository

### ISSUE THREAD

**Issue by jeffreydurieux** [g14r/neurohackmap#20]
Hi, the NeuroMap 2.csv is not in your repository. So the Neuromap_code.ipynb does not work.
Could you add the NeuroMap 2.csv file to the repo?

**Comment by g14r** [comment]
Hi Jeffrey, we initially left the full dataset out for reasons of privacy, but have now created a subset of it (neuromap_data_subset.csv) stripped of the unnecessary information. Try visualizing it with Neurohackmap_code_subset.ipynb

**Comment by jeffreydurieux** [comment]
Hi Giacomo, thanks! Will try it out.
Best,
Jeffrey
